### ISSUE TITLE
move the minimum required version of requests back a couple of minor versions

### ISSUE THREAD

**Issue by haleemur** [1Password/connect-sdk-python#18]
### Summary
currently, the minimum requests version is [`2.24.0`](https://github.com/1Password/connect-sdk-python/blob/main/pyproject.toml#L16)

another library i depend on has requests pinned to `requests==2.23`. i can't install the connect sdk in that project as a result, because the project uses poetry, which identifies the dependency version conflict.

### Use cases

requests is a widely used python library & chances are any python project will already have requests as a dependency. poetry will refuse to install libraries if dependency resolution fails. it would help adoption of the connect client if it were more permissive in its dependency on requests.

### Proposed solution

pushing the minimum version to `2.23.0` would solve my issue, but maybe it would be beneficial for adoption if the minimum version was always at least [2 years old](https://github.com/psf/requests/blob/master/HISTORY.md#2220-2019-05-15)

**Comment by edif2008** [comment]
Hey @haleemur,

Apologies for the late reply.

Could you tell me if the issue described is still applicable today?
Based on your proposed solution, the minimum version should be at least 2 years old, which is the case for `2.24.0` today. Therefore, I'm currently hesitant in saying whether it's a good thing to move the minimum requirement for now.

**Comment by edif2008** [comment]
Closing issue. Feel free to reopen if it's still valid.
