### ISSUE TITLE
where is `Item` defined? It doesn't seem to be any local, class or global identifier

### ISSUE THREAD

**Issue by haleemur** [1Password/connect-sdk-python#19]
https://github.com/1Password/connect-sdk-python/blob/main/src/onepasswordconnectsdk/models/summary_item.py#L394
&
https://github.com/1Password/connect-sdk-python/blob/main/src/onepasswordconnectsdk/models/summary_item.py#L401

a comparison is made to check if `other` is an instance of `Item`, but where is `Item` coming from?

**Comment by SimonBarendse** [comment]
`Item` is defined here: https://github.com/1Password/connect-sdk-python/blob/10d15e34e868384b22da749ac6789a06f5abd125/src/onepasswordconnectsdk/models/item.py#L19

It seems like there's an import missing and I've opened #20 to address this.

Thank you for raising this issue! :raised_hands:
