### ISSUE TITLE
SSH_KEY is an invalid value for 'category'

### ISSUE THREAD

**Issue by floriandaniel** [1Password/connect-sdk-python#53]
Hello !
I'm trying to get an SSH key from 1Password Connect Server with the API. But I'm getting the following issue : 

```
ValueError: Invalid value for `category` (SSH_KEY), must be one of ['LOGIN', 'PASSWORD', 'SERVER', 'DATABASE', 'CREDIT_CARD', 'MEMBERSHIP', 'PASSPORT', 'SOFTWARE_LICENSE', 'OUTDOOR_LICENSE', 'SECURE_NOTE', 'WIRELESS_ROUTER', 'BANK_ACCOUNT', 'DRIVER_LICENSE', 'IDENTITY', 'REWARD_PROGRAM', 'DOCUMENT', 'EMAIL_ACCOUNT', 'SOCIAL_SECURITY_NUMBER', 'API_CREDENTIAL', 'CUSTOM']
```

Do I only need to submit a new PR ? including the new category type "SSH_KEY"

**Comment by ftasbasi** [comment]
I get the same issue when I try to get items in a given vault id `client.get_items(str(vault.id))`

**Comment by edif2008** [comment]
Hey @floriandaniel,
As @ftasbasi suggested, updating the Connect Python SDK to the latest version (`1.3.0`) should address the issue you're running to.
That release contains https://github.com/1Password/connect-sdk-python/pull/54, which solves the unexpected error for new categories that are added to Connect.

Closing the issue for now. Feel free to re-open if you still run into this issue with the latest version of the SDK.
