### ISSUE TITLE
SDK to support async operations

### ISSUE THREAD

**Issue by HaddadJoe** [1Password/connect-sdk-python#58]
### Summary
When downloading a bunch of items to initialize our app, we would like to benefit from async io operation to perform multiple bulk downloads. Current implementation force us to download these sequentially or having to resort to using threading which create a large overhead.

### Use cases
Initializing an app on runtime to download all needed passwords

### Proposed solution
Implement the internal request builder using built-in async.io or any other async library

### Is there a workaround to accomplish this today?
yes, running using threads

### References & Prior Work
no sure

**Comment by HaddadJoe** [comment]
hey @volodymyrZotov what's the situation on that ?

**Comment by volodymyrZotov** [comment]
Hi @HaddadJoe. Thank you for raising this feature request! Sorry for a such a delay with that. This is still on our team's radar. I'll try to come back on it as soon as possible, address all the PR comments and bring it into a good shape soon.

**Comment by volodymyrZotov** [comment]
Hi @HaddadJoe . I expect to make a release with that by the end of the week.

**Comment by volodymyrZotov** [comment]
That would be great, thanks @HaddadJoe !
