### ISSUE TITLE
Drop Python 2 Support

### ISSUE THREAD

**Issue by HaddadJoe** [1Password/connect-sdk-python#59]
### Summary
Python 2 end of life was almost 3 years ago. The sdk should drop support for that and remove the six package.

### Use cases
We're trying to use the python sdk in a modern project however due to old requirements, our dependency manager is failing to install the sdk with other incompatible libraries. 

### Proposed solution
- Drop support for python2 and make necessary modifications to support python3
- Remove six package
- Test code on newer versions of python
- Optional: Upgrade request version

### Is there a workaround to accomplish this today?
Not that i'm aware off (without potentially breaking some library dependencies)

### References & Prior Work
Again, happy to open PRs if it's a direction you'd explore

**Comment by volodymyrZotov** [comment]
Hey @HaddadJoe! Thank you for raising this!
There is a PR I opened for that #61 .
