### ISSUE TITLE
Add excludeCharacters property to GeneratorRecipe

### ISSUE THREAD

**Issue by volodymyrZotov** [1Password/connect-sdk-python#79]
Currently `GeneratorRecipe` doesn't have `excludeCharacters` property.

This feature request is to add `excludeCharacters: string` to the `GeneratorRecipe` which is a list of all characters that should be excluded from generated passwords. 

https://developer.1password.com/docs/connect/connect-api-reference#item-generatorrecipe-object

**Comment by davidtran001** [comment]
I have created a [PR](https://github.com/1Password/connect-sdk-python/pull/83) that addresses this issue.
